BASE_PATH: 
paginate: 10 # pagination based on number of posts
paginate_path: "page:num" #pagination generated sub path format
encoding: utf-8
permalink: /:categories/:title.html

markdown: redcarpet
highlighter: false


name: 卓文理
title: 卓文理

author:
  name: 卓文理
  email: 531840344@qq.com
  github: zhuowenli
  twitter: vnnlee zhuo
  bio: 我在这里，高清有码！

rss_path: sitemap.xml

